apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  labels:
    machine.openshift.io/cluster-api-cluster: cluster-4d56-k9qxl
  name: cluster-4d56-k9qxl-infra-us-east-2a
  namespace: openshift-machine-api
spec:
  replicas: 2
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: cluster-4d56-k9qxl 
      machine.openshift.io/cluster-api-machineset: cluster-4d56-k9qxl-infra-us-east-2a 
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: cluster-4d56-k9qxl 
        machine.openshift.io/cluster-api-machine-role: worker 
        machine.openshift.io/cluster-api-machine-type: worker 
        machine.openshift.io/cluster-api-machineset: cluster-4d56-k9qxl-infra-us-east-2a 
    spec:
      metadata:
        labels:
          node-role.kubernetes.io/infra: ""
      providerSpec:
        value:
          ami:
            id: ami-0649fd5d42859bdfc 
          apiVersion: awsproviderconfig.openshift.io/v1beta1
          blockDevices:
            - ebs:
                iops: 0
                volumeSize: 120
                volumeType: gp2
          credentialsSecret:
            name: aws-cloud-credentials
          deviceIndex: 0
          iamInstanceProfile:
            id: cluster-4d56-k9qxl-worker-profile 
          instanceType: m4.xlarge
          kind: AWSMachineProviderConfig
          placement:
            availabilityZone: us-east-2a
            region: us-east-2
          securityGroups:
            - filters:
                - name: tag:Name
                  values:
                    - cluster-4d56-k9qxl-worker-sg 
          subnet:
            filters:
              - name: tag:Name
                values:
                  - cluster-4d56-k9qxl-private-us-east-2a
          tags:
            - name: kubernetes.io/cluster/cluster-4d56-k9qxl 
              value: owned
          userDataSecret:
            name: worker-user-data
