apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  creationTimestamp: "2019-12-10T17:01:19Z"
  generation: 2
  labels:
    machine.openshift.io/cluster-api-cluster: bd5e-sxphr
    machine.openshift.io/cluster-api-machine-role: worker
    machine.openshift.io/cluster-api-machine-type: worker
  name: logging-1a
  namespace: openshift-machine-api
  resourceVersion: "67935"
  selfLink: /apis/machine.openshift.io/v1beta1/namespaces/openshift-machine-api/machinesets/logging-1a
  uid: af9b4037-1b6e-11ea-a220-fa163e7f881b
spec:
  replicas: 1
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: bd5e-sxphr
      machine.openshift.io/cluster-api-machineset: logging-1a
  template:
    metadata:
      creationTimestamp: null
      labels:
        machine.openshift.io/cluster-api-cluster: bd5e-sxphr
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: logging-1a
    spec:
      metadata:
        labels:
          node-role.kubernetes.io/logging: ""
      providerSpec:
        value:
          apiVersion: openstackproviderconfig.openshift.io/v1alpha1
          cloudName: openstack
          cloudsSecret:
            name: openstack-cloud-credentials
            namespace: openshift-machine-api
          flavor: 4c16g30d
          image: rhcos-ocp42
          kind: OpenstackProviderSpec
          networks:
          - filter: {}
            subnets:
            - filter:
                name: bd5e-ocp-subnet
          securityGroups:
          - filter: {}
            name: bd5e-worker_sg
          serverMetadata:
            Name: bd5e-sxphr-worker
            openshiftClusterID: bd5e-sxphr
          tags:
          - openshiftClusterID=bd5e-sxphr
          trunk: true
          userDataSecret:
            name: worker-user-data
taints:
      - key: logging
        value: reserved
        effect: NoSchedule
      - key: logging
        value: reserved
        effect: NoExecute
